theme: jekyll-theme-cayman
title: Organización/Ciencia de Datos 7506-9558-TA047
description: Cátedra Martinelli

keep_files: ["visus", "pdfs", "imgs"]
include:
  - "visus"
  - "pdfs"
  - "imgs"
